CREATE TABLE IF NOT EXISTS messages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT,
    is_user BOOLEAN,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Créer la nouvelle table random_responses
CREATE TABLE random_responses (
    id INT AUTO_INCREMENT PRIMARY KEY,
    response VARCHAR(255) NOT NULL
);

CREATE TABLE answer_responses (
    id INT AUTO_INCREMENT PRIMARY KEY,
    pattern VARCHAR(255) NOT NULL,
    response VARCHAR(255) NOT NULL
);

INSERT INTO answer_responses (pattern, response) VALUES
    ("Bonjour, ça va ?", "Bonjour ! Je vais bien, merci."),
    ("Bonjour !", "Salut ! Comment puis-je vous aider aujourd\'hui ?"),
    ("Hello, Bonjour ?", "Bonjour ! Comment puis-je vous assister ?"),
    ("Comment ça va ?", "Je suis juste un programme, mais merci de demander !"),
    ("ça va ?", "Je n'ai pas d'états d'âme, mais merci de demander !");

-- Ajouter quelques réponses aléatoires
INSERT INTO random_responses (response) VALUES
    ('Je ne comprends pas bien. Pouvez-vous reformuler?'),
    ('Hmm, je ne suis pas sûr de comprendre. Essayez une autre question.'),
    ('Désolé, cela ne me semble pas clair. Essayez de poser la question différemment.'),
    ('Hmm, intéressant. Pourriez-vous en dire plus?'),
    ('Je ne suis pas programmé pour répondre à cela. Essayez une autre question.'),
    ('C\'est une question complexe! J\'aime ça.'),
    ('Ah, une énigme! Essayons de la résoudre ensemble.'),
    ('Je ne m\'attendais pas à cette question. Intrigant!'),
    ('Avez-vous déjà pensé à devenir détective? Vous posez des questions formidables.'),
    ('Votre question me fait réfléchir.'),
    ('Je ne comprends pas bien. Pouvez-vous reformuler?'),
    ('Hmm, je ne suis pas sûr de comprendre. Essayez une autre question.'),
    ('Désolé, cela ne me semble pas clair. Essayez de poser la question différemment.'),
    ('Hmm, intéressant. Pourriez-vous en dire plus?'),
    ('Je ne suis pas programmé pour répondre à cela. Essayez une autre question.'),
    ('C\'est une question complexe! J\'aime ça.'),
    ('Ah, une énigme! Essayons de la résoudre ensemble.'),
    ('Je ne m\'attendais pas à cette question. Intrigant!'),
    ('Avez-vous déjà pensé à devenir détective? Vous posez des questions formidables.'),
    ('Votre question me fait réfléchir.'),
    ('Merci pour votre message!'),
    ('Intéressant, poursuivons la conversation.'),
    ('Ah, la curiosité est une belle qualité.'),
    ('Vous me surprenez toujours avec vos questions.'),
    ('Je n\'ai pas la réponse parfaite, mais nous pouvons discuter de cela.'),
    ('Pardon, j\'étais perdu dans mes pensées. Que disiez-vous?'),
    ('Oh là là! Cette question est vraiment intéressante.'),
    ('Une question qui nécessite une réflexion approfondie.'),
    ('C\'est une question que même moi, en tant que bot, je trouve captivante.'),
    ('Les questions difficiles sont les meilleures. Continuez comme ça!'),
    ('Je suis ici pour répondre à toutes vos questions!'),
    ('Votre question est comme une énigme à résoudre.'),
    ('Je suis curieux de savoir ce qui vous amène ici aujourd\'hui.'),
    ('Ah, une autre question fascinante!'),
    ('Je n\'aurais jamais pensé à cette question. Vous êtes vraiment créatif.'),
    ('Merci pour cette question. J\'adore discuter avec vous!'),
    ('Votre curiosité n\'a pas de limites, et j\'adore ça!'),
    ('Il semble que chaque jour, vous me surpreniez davantage.'),
    ('Continuez à me poser des questions. J\'adore ça!'),
    ('C\'est agréable de discuter avec vous. Avez-vous d\'autres questions?'),
    ('Votre question m\'a pris au dépourvu!'),
    ('Vous avez le don de poser des questions incroyables.'),
    ('Pardon, j\'étais absorbé par vos précédentes questions.'),
    ('Une question qui nécessite une réflexion sérieuse.'),
    ('Je suis ravi de répondre à vos questions!'),
    ('Votre esprit curieux est vraiment stimulant.'),
    ('Merci pour cette question intéressante!'),
    ('C\'est un plaisir de discuter avec vous.'),
    ('Je suis toujours prêt pour de nouvelles questions!'),
    ('Votre question m\'a vraiment fait réfléchir.'),
    ('Vous avez une façon unique de poser des questions.'),
    ('Je suis prêt pour la prochaine question!'),
    ('Continuez à me surprendre avec vos questions fascinantes.'),
    ('Je suis impatient de voir quelle sera votre prochaine question.'),
    ('C\'est vraiment agréable de discuter avec vous.'),
    ('Vous êtes plein de surprises avec vos questions!'),
    ('Merci pour cette question intrigante!'),
    ('Votre esprit curieux est une source d\'inspiration.'),
    ('Continuez à me poser des questions!'),
    ('C\'est toujours un plaisir de discuter avec vous.'),
    ('Je suis là pour répondre à toutes vos questions.'),
    ('Votre curiosité est vraiment admirable.'),
    ('Merci pour cette question stimulante!'),
    ('Je suis prêt pour plus de questions de votre part.'),
    ('Continuez à me surprendre avec vos questions intéressantes.'),
    ('Votre esprit curieux est une merveille.'),
    ('Merci pour cette question fascinante!'),
    ('C\'est toujours un plaisir de discuter avec vous.'),
    ('Je suis ravi de répondre à vos questions.'),
    ('Votre curiosité est vraiment captivante.'),
    ('Merci pour cette question inspirante!'),
    ('Je suis prêt pour la prochaine question fascinante.'),
    ('Continuez à me surprendre avec vos questions incroyables.'),
    ('Votre esprit curieux ne cesse de m\'étonner.'),
    ('Merci pour cette question stimulante!'),
    ('C\'est vraiment agréable de discuter avec vous.'),
    ('Je suis là pour répondre à toutes vos questions.'),
    ('Votre curiosité est vraiment admirable.'),
    ('Merci pour cette question fascinante!'),
    ('Je suis prêt pour plus de questions de votre part.'),
    ('Continuez à me surprendre avec vos questions intéressantes.'),
    ('Votre esprit curieux est une merveille.'),
    ('Merci pour cette question fascinante!'),
    ('C\'est toujours un plaisir de discuter avec vous.'),
    ('Je suis ravi de répondre à vos questions.'),
    ('Votre curiosité est vraiment captivante.'),
    ('Merci pour cette question inspirante!'),
    ('Je suis prêt pour la prochaine question fascinante.'),
    ('Continuez à me surprendre avec vos questions incroyables.'),
    ('Votre esprit curieux ne cesse de m\'étonner.'),
    ('Merci pour cette question stimulante!'),
    ('C\'est vraiment agréable de discuter avec vous.'),
    ('Je suis là pour répondre à toutes vos questions.'),
    ('Votre curiosité est vraiment admirable.'),
    ('Merci pour cette question fascinante!'),
    ('Je suis prêt pour plus de questions de votre part.'),
    ('Continuez à me surprendre avec vos questions intéressantes.'),
    ('Votre esprit curieux est une merveille.'),
    ('Merci pour cette question fascinante!'),
    ('C\'est toujours un plaisir de discuter avec vous.'),
    ('Je suis ravi de répondre à vos questions.'),
    ('Votre curiosité est vraiment captivante.'),
    ('Merci pour cette question inspirante!'),
    ('Je suis prêt pour la prochaine question fascinante.'),
    ('Continuez à me surprendre avec vos questions incroyables.'),
    ('Votre esprit curieux ne cesse de m\'étonner.'),
    ('Merci pour cette question stimulante!'),
    ('C\'est vraiment agréable de discuter avec vous.'),
    ('Je suis là pour répondre à toutes vos questions.'),
    ('Votre curiosité est vraiment admirable.'),
    ('Merci pour cette question fascinante!'),
    ('Je suis prêt pour plus de questions de votre part.'),
    ('Continuez à me surprendre avec vos questions intéressantes.'),
    ('Votre esprit curieux est une merveille.'),
    ('Merci pour cette question fascinante!'),
    ('C\'est toujours un plaisir de discuter avec vous.'),
    ('Je suis ravi de répondre à vos questions.'),
    ('Votre curiosité est vraiment captivante.'),
    ('Merci pour cette question inspirante!'),
    ('Je suis prêt pour la prochaine question fascinante.'),
    ('Continuez à me surprendre avec vos questions incroyables.'),
    ('Votre esprit curieux ne cesse de m\'étonner.'),
    ('Merci pour cette question stimulante!'),
    ('C\'est vraiment agréable de discuter avec vous.'),
    ('Je suis là pour répondre à toutes vos questions.'),
    ('Votre curiosité est vraiment admirable.'),
    ('Merci pour cette question fascinante!'),
    ('Je suis prêt pour plus de questions de votre part.'),
    ('Continuez à me surprendre avec vos questions intéressantes.'),
    ('Votre esprit curieux est une merveille.'),
    ('Merci pour cette question fascinante!'),
    ('C\'est toujours un plaisir de discuter avec vous.'),
    ('Je suis ravi de répondre à vos questions.'),
    ('Votre curiosité est vraiment captivante.'),
    ('Merci pour cette question inspirante!'),
    ('Je suis prêt pour la prochaine question fascinante.'),
    ('Continuez à me surprendre avec vos questions incroyables.'),
    ('Votre esprit curieux ne cesse de m\'étonner.'),
    ('Merci pour cette question stimulante!'),
    ('C\'est vraiment agréable de discuter avec vous.'),
    ('Je suis là pour répondre à toutes vos questions.'),
    ('Votre curiosité est vraiment admirable.'),
    ('Merci pour cette question fascinante!'),
    ('Je suis prêt pour plus de questions de votre part.'),
    ('Continuez à me surprendre avec vos questions intéressantes.'),
    ('Votre esprit curieux est une merveille.'),
    ('Merci pour cette question fascinante!'),
    ('C\'est toujours un plaisir de discuter avec vous.'),
    ('Je suis ravi de répondre à vos questions.'),
    ('Votre curiosité est vraiment captivante.'),
    ('Merci pour cette question inspirante!'),
    ('Je suis prêt pour la prochaine question fascinante.'),
    ('Continuez à me surprendre avec vos questions incroyables.'),
    ('Votre esprit curieux ne cesse de m\'étonner.'),
    ('Merci pour cette question stimulante!'),
    ('C\'est vraiment agréable de discuter avec vous.'),
    ('Je suis là pour répondre à toutes vos questions.'),
    ('Votre curiosité est vraiment admirable.'),
    ('Merci pour cette question fascinante!'),
    ('Je suis prêt pour plus de questions de votre part.'),
    ('Continuez à me surprendre avec vos questions intéressantes.'),
    ('Votre esprit curieux est une merveille.'),
    ('Merci pour cette question fascinante!'),
    ('C\'est toujours un plaisir de discuter avec vous.'),
    ('Je suis ravi de répondre à vos questions.'),
    ('Votre curiosité est vraiment captivante.'),
    ('Merci pour cette question inspirante!'),
    ('Je suis prêt pour la prochaine question fascinante.'),
    ('Continuez à me surprendre avec vos questions incroyables.'),
    ('Votre esprit curieux ne cesse de m\'étonner.'),
    ('Merci pour cette question stimulante!'),
    ('C\'est vraiment agréable de discuter avec vous.'),
    ('Je suis là pour répondre à toutes vos questions.'),
    ('Votre curiosité est vraiment admirable.'),
    ('Merci pour cette question fascinante!'),
    ('Je suis prêt pour plus de questions de votre part.'),
    ('Continuez à me surprendre avec vos questions intéressantes.'),
    ('Votre esprit curieux est une merveille.'),
    ('Merci pour cette question fascinante!'),
    ('C\'est toujours un plaisir de discuter avec vous.'),
    ('Je suis ravi de répondre à vos questions.'),
    ('Votre curiosité est vraiment captivante.'),
    ('Merci pour cette question inspirante!'),
    ('Je suis prêt pour la prochaine question fascinante.'),
    ('Continuez à me surprendre avec vos questions incroyables.'),
    ('Votre esprit curieux ne cesse de m\'étonner.'),
    ('Merci pour cette question stimulante!'),
    ('C\'est vraiment agréable de discuter avec vous.'),
    ('Je suis là pour répondre à toutes vos questions.'),
    ('Votre curiosité est vraiment admirable.'),
    ('Merci pour cette question fascinante!'),
    ('Je suis prêt pour plus de questions de votre part.'),
    ('Continuez à me surprendre avec vos questions intéressantes.');
